// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.8
// source: auth.proto

package auth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestDecodeToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RequestDecodeToken) Reset() {
	*x = RequestDecodeToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestDecodeToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDecodeToken) ProtoMessage() {}

func (x *RequestDecodeToken) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDecodeToken.ProtoReflect.Descriptor instead.
func (*RequestDecodeToken) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

type ResponsesDecodeToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username    string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	RoleLabel   string `protobuf:"bytes,3,opt,name=role_label,json=roleLabel,proto3" json:"role_label,omitempty"`
	LastLoginAt string `protobuf:"bytes,4,opt,name=last_login_at,json=lastLoginAt,proto3" json:"last_login_at,omitempty"`
}

func (x *ResponsesDecodeToken) Reset() {
	*x = ResponsesDecodeToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponsesDecodeToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponsesDecodeToken) ProtoMessage() {}

func (x *ResponsesDecodeToken) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponsesDecodeToken.ProtoReflect.Descriptor instead.
func (*ResponsesDecodeToken) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
}

func (x *ResponsesDecodeToken) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResponsesDecodeToken) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ResponsesDecodeToken) GetRoleLabel() string {
	if x != nil {
		return x.RoleLabel
	}
	return ""
}

func (x *ResponsesDecodeToken) GetLastLoginAt() string {
	if x != nil {
		return x.LastLoginAt
	}
	return ""
}

type ResponseUserDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username          string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email             string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	LastLoginAt       int64  `protobuf:"varint,4,opt,name=last_login_at,json=lastLoginAt,proto3" json:"last_login_at,omitempty"`
	Role              int64  `protobuf:"varint,5,opt,name=role,proto3" json:"role,omitempty"`
	RoleLabel         string `protobuf:"bytes,6,opt,name=role_label,json=roleLabel,proto3" json:"role_label,omitempty"`
	Name              string `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Phone             string `protobuf:"bytes,8,opt,name=phone,proto3" json:"phone,omitempty"`
	Address           string `protobuf:"bytes,9,opt,name=address,proto3" json:"address,omitempty"`
	JobTypeId         int64  `protobuf:"varint,10,opt,name=job_type_id,json=jobTypeId,proto3" json:"job_type_id,omitempty"`
	JobType           string `protobuf:"bytes,11,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	EducationLevelId  int64  `protobuf:"varint,12,opt,name=education_level_id,json=educationLevelId,proto3" json:"education_level_id,omitempty"`
	EducationLevel    string `protobuf:"bytes,13,opt,name=education_level,json=educationLevel,proto3" json:"education_level,omitempty"`
	BirthDate         string `protobuf:"bytes,14,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	Rt                string `protobuf:"bytes,15,opt,name=rt,proto3" json:"rt,omitempty"`
	Rw                string `protobuf:"bytes,16,opt,name=rw,proto3" json:"rw,omitempty"`
	VillageId         int64  `protobuf:"varint,17,opt,name=village_id,json=villageId,proto3" json:"village_id,omitempty"`
	Village           string `protobuf:"bytes,18,opt,name=village,proto3" json:"village,omitempty"`
	DistrictId        int64  `protobuf:"varint,19,opt,name=district_id,json=districtId,proto3" json:"district_id,omitempty"`
	District          string `protobuf:"bytes,20,opt,name=district,proto3" json:"district,omitempty"`
	RegencyId         int64  `protobuf:"varint,21,opt,name=regency_id,json=regencyId,proto3" json:"regency_id,omitempty"`
	Regency           string `protobuf:"bytes,22,opt,name=regency,proto3" json:"regency,omitempty"`
	Latitude          string `protobuf:"bytes,23,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude         string `protobuf:"bytes,24,opt,name=longitude,proto3" json:"longitude,omitempty"`
	PhotoUrl          string `protobuf:"bytes,25,opt,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"`
	Facebook          string `protobuf:"bytes,26,opt,name=facebook,proto3" json:"facebook,omitempty"`
	Twitter           string `protobuf:"bytes,27,opt,name=twitter,proto3" json:"twitter,omitempty"`
	Instagram         string `protobuf:"bytes,28,opt,name=instagram,proto3" json:"instagram,omitempty"`
	PasswordUpdatedAt int64  `protobuf:"varint,29,opt,name=password_updated_at,json=passwordUpdatedAt,proto3" json:"password_updated_at,omitempty"`
	ProfileUpdatedAt  int64  `protobuf:"varint,30,opt,name=profile_updated_at,json=profileUpdatedAt,proto3" json:"profile_updated_at,omitempty"`
	LastAccessAt      int64  `protobuf:"varint,31,opt,name=last_access_at,json=lastAccessAt,proto3" json:"last_access_at,omitempty"`
}

func (x *ResponseUserDetail) Reset() {
	*x = ResponseUserDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseUserDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseUserDetail) ProtoMessage() {}

func (x *ResponseUserDetail) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseUserDetail.ProtoReflect.Descriptor instead.
func (*ResponseUserDetail) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseUserDetail) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResponseUserDetail) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ResponseUserDetail) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ResponseUserDetail) GetLastLoginAt() int64 {
	if x != nil {
		return x.LastLoginAt
	}
	return 0
}

func (x *ResponseUserDetail) GetRole() int64 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *ResponseUserDetail) GetRoleLabel() string {
	if x != nil {
		return x.RoleLabel
	}
	return ""
}

func (x *ResponseUserDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResponseUserDetail) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ResponseUserDetail) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ResponseUserDetail) GetJobTypeId() int64 {
	if x != nil {
		return x.JobTypeId
	}
	return 0
}

func (x *ResponseUserDetail) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *ResponseUserDetail) GetEducationLevelId() int64 {
	if x != nil {
		return x.EducationLevelId
	}
	return 0
}

func (x *ResponseUserDetail) GetEducationLevel() string {
	if x != nil {
		return x.EducationLevel
	}
	return ""
}

func (x *ResponseUserDetail) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *ResponseUserDetail) GetRt() string {
	if x != nil {
		return x.Rt
	}
	return ""
}

func (x *ResponseUserDetail) GetRw() string {
	if x != nil {
		return x.Rw
	}
	return ""
}

func (x *ResponseUserDetail) GetVillageId() int64 {
	if x != nil {
		return x.VillageId
	}
	return 0
}

func (x *ResponseUserDetail) GetVillage() string {
	if x != nil {
		return x.Village
	}
	return ""
}

func (x *ResponseUserDetail) GetDistrictId() int64 {
	if x != nil {
		return x.DistrictId
	}
	return 0
}

func (x *ResponseUserDetail) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *ResponseUserDetail) GetRegencyId() int64 {
	if x != nil {
		return x.RegencyId
	}
	return 0
}

func (x *ResponseUserDetail) GetRegency() string {
	if x != nil {
		return x.Regency
	}
	return ""
}

func (x *ResponseUserDetail) GetLatitude() string {
	if x != nil {
		return x.Latitude
	}
	return ""
}

func (x *ResponseUserDetail) GetLongitude() string {
	if x != nil {
		return x.Longitude
	}
	return ""
}

func (x *ResponseUserDetail) GetPhotoUrl() string {
	if x != nil {
		return x.PhotoUrl
	}
	return ""
}

func (x *ResponseUserDetail) GetFacebook() string {
	if x != nil {
		return x.Facebook
	}
	return ""
}

func (x *ResponseUserDetail) GetTwitter() string {
	if x != nil {
		return x.Twitter
	}
	return ""
}

func (x *ResponseUserDetail) GetInstagram() string {
	if x != nil {
		return x.Instagram
	}
	return ""
}

func (x *ResponseUserDetail) GetPasswordUpdatedAt() int64 {
	if x != nil {
		return x.PasswordUpdatedAt
	}
	return 0
}

func (x *ResponseUserDetail) GetProfileUpdatedAt() int64 {
	if x != nil {
		return x.ProfileUpdatedAt
	}
	return 0
}

func (x *ResponseUserDetail) GetLastAccessAt() int64 {
	if x != nil {
		return x.LastAccessAt
	}
	return 0
}

var File_auth_proto protoreflect.FileDescriptor

var file_auth_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x61, 0x75,
	0x74, 0x68, 0x22, 0x14, 0x0a, 0x12, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x65, 0x63,
	0x6f, 0x64, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x85, 0x01, 0x0a, 0x14, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x72, 0x6f, 0x6c, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x22, 0x0a, 0x0d,
	0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x41, 0x74,
	0x22, 0xa0, 0x07, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x22, 0x0a, 0x0d, 0x6c, 0x61, 0x73,
	0x74, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x41, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x72, 0x6f, 0x6c,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x6f, 0x6c, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x1e, 0x0a, 0x0b, 0x6a, 0x6f, 0x62, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6a, 0x6f, 0x62, 0x54, 0x79,
	0x70, 0x65, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6a, 0x6f, 0x62, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6a, 0x6f, 0x62, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x2c, 0x0a, 0x12, 0x65, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x65, 0x64, 0x75,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x27, 0x0a,
	0x0f, 0x65, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x65, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x69, 0x72, 0x74, 0x68, 0x5f,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x69, 0x72, 0x74,
	0x68, 0x44, 0x61, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x72, 0x74, 0x18, 0x0f, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x72, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x72, 0x77, 0x18, 0x10, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x72, 0x77, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x69, 0x6c, 0x6c, 0x61, 0x67, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x11, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x76, 0x69, 0x6c, 0x6c, 0x61,
	0x67, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x69, 0x6c, 0x6c, 0x61, 0x67, 0x65, 0x18,
	0x12, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x69, 0x6c, 0x6c, 0x61, 0x67, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x13, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x18, 0x14, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72,
	0x65, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x15, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x72, 0x65, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65,
	0x67, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x16, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x67,
	0x65, 0x6e, 0x63, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x18, 0x17, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x18, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x19, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x55, 0x72, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x66,
	0x61, 0x63, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x18, 0x1a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66,
	0x61, 0x63, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x77, 0x69, 0x74, 0x74,
	0x65, 0x72, 0x18, 0x1b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x77, 0x69, 0x74, 0x74, 0x65,
	0x72, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x18, 0x1c,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x12,
	0x2e, 0x0a, 0x13, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x1d, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x2c, 0x0a, 0x12, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x1e, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x70, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x24, 0x0a,
	0x0e, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x61, 0x74, 0x18,
	0x1f, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x41, 0x74, 0x32, 0xa4, 0x01, 0x0a, 0x0b, 0x41, 0x75, 0x74, 0x68, 0x48, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x72, 0x12, 0x43, 0x0a, 0x0b, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x18, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x1a, 0x2e, 0x61,
	0x75, 0x74, 0x68, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x44, 0x65, 0x63,
	0x6f, 0x64, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x50, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x42, 0x79, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x18, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x1a, 0x18, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2e,
	0x2f, 0x61, 0x75, 0x74, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_auth_proto_rawDescOnce sync.Once
	file_auth_proto_rawDescData = file_auth_proto_rawDesc
)

func file_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_rawDescData = protoimpl.X.CompressGZIP(file_auth_proto_rawDescData)
	})
	return file_auth_proto_rawDescData
}

var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_auth_proto_goTypes = []interface{}{
	(*RequestDecodeToken)(nil),   // 0: auth.RequestDecodeToken
	(*ResponsesDecodeToken)(nil), // 1: auth.ResponsesDecodeToken
	(*ResponseUserDetail)(nil),   // 2: auth.ResponseUserDetail
}
var file_auth_proto_depIdxs = []int32{
	0, // 0: auth.AuthHandler.DecodeToken:input_type -> auth.RequestDecodeToken
	0, // 1: auth.AuthHandler.GetUserDetailByAccessToken:input_type -> auth.RequestDecodeToken
	1, // 2: auth.AuthHandler.DecodeToken:output_type -> auth.ResponsesDecodeToken
	2, // 3: auth.AuthHandler.GetUserDetailByAccessToken:output_type -> auth.ResponseUserDetail
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_auth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestDecodeToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponsesDecodeToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseUserDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_auth_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_rawDesc = nil
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AuthHandlerClient is the client API for AuthHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthHandlerClient interface {
	DecodeToken(ctx context.Context, in *RequestDecodeToken, opts ...grpc.CallOption) (*ResponsesDecodeToken, error)
	GetUserDetailByAccessToken(ctx context.Context, in *RequestDecodeToken, opts ...grpc.CallOption) (*ResponseUserDetail, error)
}

type authHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthHandlerClient(cc grpc.ClientConnInterface) AuthHandlerClient {
	return &authHandlerClient{cc}
}

func (c *authHandlerClient) DecodeToken(ctx context.Context, in *RequestDecodeToken, opts ...grpc.CallOption) (*ResponsesDecodeToken, error) {
	out := new(ResponsesDecodeToken)
	err := c.cc.Invoke(ctx, "/auth.AuthHandler/DecodeToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authHandlerClient) GetUserDetailByAccessToken(ctx context.Context, in *RequestDecodeToken, opts ...grpc.CallOption) (*ResponseUserDetail, error) {
	out := new(ResponseUserDetail)
	err := c.cc.Invoke(ctx, "/auth.AuthHandler/GetUserDetailByAccessToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthHandlerServer is the server API for AuthHandler service.
type AuthHandlerServer interface {
	DecodeToken(context.Context, *RequestDecodeToken) (*ResponsesDecodeToken, error)
	GetUserDetailByAccessToken(context.Context, *RequestDecodeToken) (*ResponseUserDetail, error)
}

// UnimplementedAuthHandlerServer can be embedded to have forward compatible implementations.
type UnimplementedAuthHandlerServer struct {
}

func (*UnimplementedAuthHandlerServer) DecodeToken(context.Context, *RequestDecodeToken) (*ResponsesDecodeToken, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecodeToken not implemented")
}
func (*UnimplementedAuthHandlerServer) GetUserDetailByAccessToken(context.Context, *RequestDecodeToken) (*ResponseUserDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserDetailByAccessToken not implemented")
}

func RegisterAuthHandlerServer(s *grpc.Server, srv AuthHandlerServer) {
	s.RegisterService(&_AuthHandler_serviceDesc, srv)
}

func _AuthHandler_DecodeToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestDecodeToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthHandlerServer).DecodeToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthHandler/DecodeToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthHandlerServer).DecodeToken(ctx, req.(*RequestDecodeToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthHandler_GetUserDetailByAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestDecodeToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthHandlerServer).GetUserDetailByAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthHandler/GetUserDetailByAccessToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthHandlerServer).GetUserDetailByAccessToken(ctx, req.(*RequestDecodeToken))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthHandler",
	HandlerType: (*AuthHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DecodeToken",
			Handler:    _AuthHandler_DecodeToken_Handler,
		},
		{
			MethodName: "GetUserDetailByAccessToken",
			Handler:    _AuthHandler_GetUserDetailByAccessToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
