// Code generated by protoc-gen-go. DO NOT EDIT.
// source: phonebook.proto

package phonebook

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetListRequest struct {
	Search               string     `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	RegencyId            int64      `protobuf:"varint,2,opt,name=regency_id,json=regencyId,proto3" json:"regency_id,omitempty"`
	DistrictId           int64      `protobuf:"varint,3,opt,name=district_id,json=districtId,proto3" json:"district_id,omitempty"`
	VillageId            int64      `protobuf:"varint,4,opt,name=village_id,json=villageId,proto3" json:"village_id,omitempty"`
	Status               *NullInt64 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Limit                int64      `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	Page                 int64      `protobuf:"varint,7,opt,name=page,proto3" json:"page,omitempty"`
	Longitude            string     `protobuf:"bytes,8,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude             string     `protobuf:"bytes,9,opt,name=latitude,proto3" json:"latitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetListRequest) Reset()         { *m = GetListRequest{} }
func (m *GetListRequest) String() string { return proto.CompactTextString(m) }
func (*GetListRequest) ProtoMessage()    {}
func (*GetListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_34db5399df65ad55, []int{0}
}

func (m *GetListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListRequest.Unmarshal(m, b)
}
func (m *GetListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListRequest.Marshal(b, m, deterministic)
}
func (m *GetListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListRequest.Merge(m, src)
}
func (m *GetListRequest) XXX_Size() int {
	return xxx_messageInfo_GetListRequest.Size(m)
}
func (m *GetListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetListRequest proto.InternalMessageInfo

func (m *GetListRequest) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

func (m *GetListRequest) GetRegencyId() int64 {
	if m != nil {
		return m.RegencyId
	}
	return 0
}

func (m *GetListRequest) GetDistrictId() int64 {
	if m != nil {
		return m.DistrictId
	}
	return 0
}

func (m *GetListRequest) GetVillageId() int64 {
	if m != nil {
		return m.VillageId
	}
	return 0
}

func (m *GetListRequest) GetStatus() *NullInt64 {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetListRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetListRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetListRequest) GetLongitude() string {
	if m != nil {
		return m.Longitude
	}
	return ""
}

func (m *GetListRequest) GetLatitude() string {
	if m != nil {
		return m.Latitude
	}
	return ""
}

type GetListResponse struct {
	Data                 []*PhoneBook `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Metadata             *Metadata    `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetListResponse) Reset()         { *m = GetListResponse{} }
func (m *GetListResponse) String() string { return proto.CompactTextString(m) }
func (*GetListResponse) ProtoMessage()    {}
func (*GetListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_34db5399df65ad55, []int{1}
}

func (m *GetListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListResponse.Unmarshal(m, b)
}
func (m *GetListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListResponse.Marshal(b, m, deterministic)
}
func (m *GetListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListResponse.Merge(m, src)
}
func (m *GetListResponse) XXX_Size() int {
	return xxx_messageInfo_GetListResponse.Size(m)
}
func (m *GetListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetListResponse proto.InternalMessageInfo

func (m *GetListResponse) GetData() []*PhoneBook {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetListResponse) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type Metadata struct {
	Page                 int64    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Total                int64    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_34db5399df65ad55, []int{2}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Metadata) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type PhoneBook struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PhoneNumbers         string   `protobuf:"bytes,2,opt,name=phone_numbers,json=phoneNumbers,proto3" json:"phone_numbers,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Latitude             string   `protobuf:"bytes,6,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            string   `protobuf:"bytes,7,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Status               int64    `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	Category             string   `protobuf:"bytes,9,opt,name=category,proto3" json:"category,omitempty"`
	Distance             string   `protobuf:"bytes,10,opt,name=distance,proto3" json:"distance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhoneBook) Reset()         { *m = PhoneBook{} }
func (m *PhoneBook) String() string { return proto.CompactTextString(m) }
func (*PhoneBook) ProtoMessage()    {}
func (*PhoneBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_34db5399df65ad55, []int{3}
}

func (m *PhoneBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhoneBook.Unmarshal(m, b)
}
func (m *PhoneBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhoneBook.Marshal(b, m, deterministic)
}
func (m *PhoneBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhoneBook.Merge(m, src)
}
func (m *PhoneBook) XXX_Size() int {
	return xxx_messageInfo_PhoneBook.Size(m)
}
func (m *PhoneBook) XXX_DiscardUnknown() {
	xxx_messageInfo_PhoneBook.DiscardUnknown(m)
}

var xxx_messageInfo_PhoneBook proto.InternalMessageInfo

func (m *PhoneBook) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PhoneBook) GetPhoneNumbers() string {
	if m != nil {
		return m.PhoneNumbers
	}
	return ""
}

func (m *PhoneBook) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PhoneBook) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PhoneBook) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *PhoneBook) GetLatitude() string {
	if m != nil {
		return m.Latitude
	}
	return ""
}

func (m *PhoneBook) GetLongitude() string {
	if m != nil {
		return m.Longitude
	}
	return ""
}

func (m *PhoneBook) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *PhoneBook) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *PhoneBook) GetDistance() string {
	if m != nil {
		return m.Distance
	}
	return ""
}

type GetDetailRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDetailRequest) Reset()         { *m = GetDetailRequest{} }
func (m *GetDetailRequest) String() string { return proto.CompactTextString(m) }
func (*GetDetailRequest) ProtoMessage()    {}
func (*GetDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_34db5399df65ad55, []int{4}
}

func (m *GetDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDetailRequest.Unmarshal(m, b)
}
func (m *GetDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDetailRequest.Marshal(b, m, deterministic)
}
func (m *GetDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDetailRequest.Merge(m, src)
}
func (m *GetDetailRequest) XXX_Size() int {
	return xxx_messageInfo_GetDetailRequest.Size(m)
}
func (m *GetDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDetailRequest proto.InternalMessageInfo

func (m *GetDetailRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetDetailResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PhoneNumbers         string   `protobuf:"bytes,2,opt,name=phone_numbers,json=phoneNumbers,proto3" json:"phone_numbers,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Latitude             string   `protobuf:"bytes,6,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            string   `protobuf:"bytes,7,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Status               int64    `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt            string   `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CategoryId           int64    `protobuf:"varint,11,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryName         string   `protobuf:"bytes,12,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	Distance             string   `protobuf:"bytes,13,opt,name=distance,proto3" json:"distance,omitempty"`
	RegencyId            int64    `protobuf:"varint,14,opt,name=regency_id,json=regencyId,proto3" json:"regency_id,omitempty"`
	RegencyName          string   `protobuf:"bytes,15,opt,name=regency_name,json=regencyName,proto3" json:"regency_name,omitempty"`
	DistrictId           int64    `protobuf:"varint,16,opt,name=district_id,json=districtId,proto3" json:"district_id,omitempty"`
	DistrictName         string   `protobuf:"bytes,17,opt,name=district_name,json=districtName,proto3" json:"district_name,omitempty"`
	VillageId            int64    `protobuf:"varint,18,opt,name=village_id,json=villageId,proto3" json:"village_id,omitempty"`
	VillageName          string   `protobuf:"bytes,19,opt,name=village_name,json=villageName,proto3" json:"village_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDetailResponse) Reset()         { *m = GetDetailResponse{} }
func (m *GetDetailResponse) String() string { return proto.CompactTextString(m) }
func (*GetDetailResponse) ProtoMessage()    {}
func (*GetDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_34db5399df65ad55, []int{5}
}

func (m *GetDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDetailResponse.Unmarshal(m, b)
}
func (m *GetDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDetailResponse.Marshal(b, m, deterministic)
}
func (m *GetDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDetailResponse.Merge(m, src)
}
func (m *GetDetailResponse) XXX_Size() int {
	return xxx_messageInfo_GetDetailResponse.Size(m)
}
func (m *GetDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDetailResponse proto.InternalMessageInfo

func (m *GetDetailResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetDetailResponse) GetPhoneNumbers() string {
	if m != nil {
		return m.PhoneNumbers
	}
	return ""
}

func (m *GetDetailResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GetDetailResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetDetailResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *GetDetailResponse) GetLatitude() string {
	if m != nil {
		return m.Latitude
	}
	return ""
}

func (m *GetDetailResponse) GetLongitude() string {
	if m != nil {
		return m.Longitude
	}
	return ""
}

func (m *GetDetailResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetDetailResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetDetailResponse) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *GetDetailResponse) GetCategoryId() int64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *GetDetailResponse) GetCategoryName() string {
	if m != nil {
		return m.CategoryName
	}
	return ""
}

func (m *GetDetailResponse) GetDistance() string {
	if m != nil {
		return m.Distance
	}
	return ""
}

func (m *GetDetailResponse) GetRegencyId() int64 {
	if m != nil {
		return m.RegencyId
	}
	return 0
}

func (m *GetDetailResponse) GetRegencyName() string {
	if m != nil {
		return m.RegencyName
	}
	return ""
}

func (m *GetDetailResponse) GetDistrictId() int64 {
	if m != nil {
		return m.DistrictId
	}
	return 0
}

func (m *GetDetailResponse) GetDistrictName() string {
	if m != nil {
		return m.DistrictName
	}
	return ""
}

func (m *GetDetailResponse) GetVillageId() int64 {
	if m != nil {
		return m.VillageId
	}
	return 0
}

func (m *GetDetailResponse) GetVillageName() string {
	if m != nil {
		return m.VillageName
	}
	return ""
}

type AddPhonebookRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumbers         string   `protobuf:"bytes,2,opt,name=phone_numbers,json=phoneNumbers,proto3" json:"phone_numbers,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	RegencyId            int64    `protobuf:"varint,5,opt,name=regency_id,json=regencyId,proto3" json:"regency_id,omitempty"`
	DistrictId           int64    `protobuf:"varint,6,opt,name=district_id,json=districtId,proto3" json:"district_id,omitempty"`
	VillageId            int64    `protobuf:"varint,7,opt,name=village_id,json=villageId,proto3" json:"village_id,omitempty"`
	Latitude             string   `protobuf:"bytes,8,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            string   `protobuf:"bytes,9,opt,name=longitude,proto3" json:"longitude,omitempty"`
	CoverImagePath       string   `protobuf:"bytes,10,opt,name=cover_image_path,json=coverImagePath,proto3" json:"cover_image_path,omitempty"`
	Status               int64    `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`
	CategoryId           int64    `protobuf:"varint,12,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPhonebookRequest) Reset()         { *m = AddPhonebookRequest{} }
func (m *AddPhonebookRequest) String() string { return proto.CompactTextString(m) }
func (*AddPhonebookRequest) ProtoMessage()    {}
func (*AddPhonebookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_34db5399df65ad55, []int{6}
}

func (m *AddPhonebookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPhonebookRequest.Unmarshal(m, b)
}
func (m *AddPhonebookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPhonebookRequest.Marshal(b, m, deterministic)
}
func (m *AddPhonebookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPhonebookRequest.Merge(m, src)
}
func (m *AddPhonebookRequest) XXX_Size() int {
	return xxx_messageInfo_AddPhonebookRequest.Size(m)
}
func (m *AddPhonebookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPhonebookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddPhonebookRequest proto.InternalMessageInfo

func (m *AddPhonebookRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddPhonebookRequest) GetPhoneNumbers() string {
	if m != nil {
		return m.PhoneNumbers
	}
	return ""
}

func (m *AddPhonebookRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *AddPhonebookRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AddPhonebookRequest) GetRegencyId() int64 {
	if m != nil {
		return m.RegencyId
	}
	return 0
}

func (m *AddPhonebookRequest) GetDistrictId() int64 {
	if m != nil {
		return m.DistrictId
	}
	return 0
}

func (m *AddPhonebookRequest) GetVillageId() int64 {
	if m != nil {
		return m.VillageId
	}
	return 0
}

func (m *AddPhonebookRequest) GetLatitude() string {
	if m != nil {
		return m.Latitude
	}
	return ""
}

func (m *AddPhonebookRequest) GetLongitude() string {
	if m != nil {
		return m.Longitude
	}
	return ""
}

func (m *AddPhonebookRequest) GetCoverImagePath() string {
	if m != nil {
		return m.CoverImagePath
	}
	return ""
}

func (m *AddPhonebookRequest) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AddPhonebookRequest) GetCategoryId() int64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

type StatusResponse struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_34db5399df65ad55, []int{7}
}

func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (m *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(m, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *StatusResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UpdatePhonebookRequest struct {
	Id                   int64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumbers         string     `protobuf:"bytes,3,opt,name=phone_numbers,json=phoneNumbers,proto3" json:"phone_numbers,omitempty"`
	Address              string     `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Description          string     `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	RegencyId            int64      `protobuf:"varint,6,opt,name=regency_id,json=regencyId,proto3" json:"regency_id,omitempty"`
	DistrictId           int64      `protobuf:"varint,7,opt,name=district_id,json=districtId,proto3" json:"district_id,omitempty"`
	VillageId            int64      `protobuf:"varint,8,opt,name=village_id,json=villageId,proto3" json:"village_id,omitempty"`
	Latitude             string     `protobuf:"bytes,9,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            string     `protobuf:"bytes,10,opt,name=longitude,proto3" json:"longitude,omitempty"`
	CoverImagePath       string     `protobuf:"bytes,11,opt,name=cover_image_path,json=coverImagePath,proto3" json:"cover_image_path,omitempty"`
	Status               *NullInt64 `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	CategoryId           int64      `protobuf:"varint,13,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpdatePhonebookRequest) Reset()         { *m = UpdatePhonebookRequest{} }
func (m *UpdatePhonebookRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePhonebookRequest) ProtoMessage()    {}
func (*UpdatePhonebookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_34db5399df65ad55, []int{8}
}

func (m *UpdatePhonebookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePhonebookRequest.Unmarshal(m, b)
}
func (m *UpdatePhonebookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePhonebookRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePhonebookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePhonebookRequest.Merge(m, src)
}
func (m *UpdatePhonebookRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePhonebookRequest.Size(m)
}
func (m *UpdatePhonebookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePhonebookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePhonebookRequest proto.InternalMessageInfo

func (m *UpdatePhonebookRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdatePhonebookRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdatePhonebookRequest) GetPhoneNumbers() string {
	if m != nil {
		return m.PhoneNumbers
	}
	return ""
}

func (m *UpdatePhonebookRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *UpdatePhonebookRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdatePhonebookRequest) GetRegencyId() int64 {
	if m != nil {
		return m.RegencyId
	}
	return 0
}

func (m *UpdatePhonebookRequest) GetDistrictId() int64 {
	if m != nil {
		return m.DistrictId
	}
	return 0
}

func (m *UpdatePhonebookRequest) GetVillageId() int64 {
	if m != nil {
		return m.VillageId
	}
	return 0
}

func (m *UpdatePhonebookRequest) GetLatitude() string {
	if m != nil {
		return m.Latitude
	}
	return ""
}

func (m *UpdatePhonebookRequest) GetLongitude() string {
	if m != nil {
		return m.Longitude
	}
	return ""
}

func (m *UpdatePhonebookRequest) GetCoverImagePath() string {
	if m != nil {
		return m.CoverImagePath
	}
	return ""
}

func (m *UpdatePhonebookRequest) GetStatus() *NullInt64 {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *UpdatePhonebookRequest) GetCategoryId() int64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

type NullString struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	IsNull               bool     `protobuf:"varint,2,opt,name=is_null,json=isNull,proto3" json:"is_null,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NullString) Reset()         { *m = NullString{} }
func (m *NullString) String() string { return proto.CompactTextString(m) }
func (*NullString) ProtoMessage()    {}
func (*NullString) Descriptor() ([]byte, []int) {
	return fileDescriptor_34db5399df65ad55, []int{9}
}

func (m *NullString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NullString.Unmarshal(m, b)
}
func (m *NullString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NullString.Marshal(b, m, deterministic)
}
func (m *NullString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NullString.Merge(m, src)
}
func (m *NullString) XXX_Size() int {
	return xxx_messageInfo_NullString.Size(m)
}
func (m *NullString) XXX_DiscardUnknown() {
	xxx_messageInfo_NullString.DiscardUnknown(m)
}

var xxx_messageInfo_NullString proto.InternalMessageInfo

func (m *NullString) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *NullString) GetIsNull() bool {
	if m != nil {
		return m.IsNull
	}
	return false
}

type NullInt64 struct {
	Value                int64    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	IsNull               bool     `protobuf:"varint,2,opt,name=is_null,json=isNull,proto3" json:"is_null,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NullInt64) Reset()         { *m = NullInt64{} }
func (m *NullInt64) String() string { return proto.CompactTextString(m) }
func (*NullInt64) ProtoMessage()    {}
func (*NullInt64) Descriptor() ([]byte, []int) {
	return fileDescriptor_34db5399df65ad55, []int{10}
}

func (m *NullInt64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NullInt64.Unmarshal(m, b)
}
func (m *NullInt64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NullInt64.Marshal(b, m, deterministic)
}
func (m *NullInt64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NullInt64.Merge(m, src)
}
func (m *NullInt64) XXX_Size() int {
	return xxx_messageInfo_NullInt64.Size(m)
}
func (m *NullInt64) XXX_DiscardUnknown() {
	xxx_messageInfo_NullInt64.DiscardUnknown(m)
}

var xxx_messageInfo_NullInt64 proto.InternalMessageInfo

func (m *NullInt64) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *NullInt64) GetIsNull() bool {
	if m != nil {
		return m.IsNull
	}
	return false
}

func init() {
	proto.RegisterType((*GetListRequest)(nil), "phonebook.GetListRequest")
	proto.RegisterType((*GetListResponse)(nil), "phonebook.GetListResponse")
	proto.RegisterType((*Metadata)(nil), "phonebook.Metadata")
	proto.RegisterType((*PhoneBook)(nil), "phonebook.PhoneBook")
	proto.RegisterType((*GetDetailRequest)(nil), "phonebook.GetDetailRequest")
	proto.RegisterType((*GetDetailResponse)(nil), "phonebook.GetDetailResponse")
	proto.RegisterType((*AddPhonebookRequest)(nil), "phonebook.AddPhonebookRequest")
	proto.RegisterType((*StatusResponse)(nil), "phonebook.StatusResponse")
	proto.RegisterType((*UpdatePhonebookRequest)(nil), "phonebook.UpdatePhonebookRequest")
	proto.RegisterType((*NullString)(nil), "phonebook.NullString")
	proto.RegisterType((*NullInt64)(nil), "phonebook.NullInt64")
}

func init() { proto.RegisterFile("phonebook.proto", fileDescriptor_34db5399df65ad55) }

var fileDescriptor_34db5399df65ad55 = []byte{
	// 888 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0x56, 0xe2, 0xfc, 0x78, 0x4e, 0xd2, 0xa4, 0x3b, 0xad, 0x8a, 0x09, 0xbb, 0x90, 0x7a, 0x6f,
	0x72, 0x81, 0x16, 0x69, 0x59, 0x71, 0x01, 0x12, 0xa2, 0x68, 0xc5, 0x62, 0x09, 0x4a, 0xe5, 0x15,
	0xd7, 0xd1, 0xd4, 0x33, 0x4a, 0x47, 0xeb, 0xd8, 0xc1, 0x1e, 0x57, 0xea, 0x35, 0x12, 0xef, 0x00,
	0x2f, 0xc1, 0xcb, 0xf0, 0x40, 0x68, 0xfe, 0x5c, 0x7b, 0x12, 0x9c, 0x5e, 0x73, 0x37, 0xf3, 0x9d,
	0x33, 0xc7, 0x73, 0xce, 0xf7, 0x9d, 0x33, 0x86, 0xf9, 0xee, 0x2e, 0xcf, 0xd8, 0x6d, 0x9e, 0x7f,
	0x78, 0xb5, 0x2b, 0x72, 0x91, 0x63, 0x54, 0x03, 0xe1, 0x9f, 0x7d, 0x98, 0xbd, 0x63, 0xe2, 0x27,
	0x5e, 0x8a, 0x98, 0xfd, 0x56, 0xb1, 0x52, 0xe0, 0x0b, 0x18, 0x95, 0x8c, 0x14, 0xc9, 0x5d, 0xd0,
	0x5b, 0xf6, 0x56, 0x28, 0x36, 0x3b, 0xfc, 0x02, 0xa0, 0x60, 0x1b, 0x96, 0x25, 0x0f, 0x6b, 0x4e,
	0x83, 0xfe, 0xb2, 0xb7, 0xf2, 0x62, 0x64, 0x90, 0x88, 0xe2, 0xcf, 0x60, 0x42, 0x79, 0x29, 0x0a,
	0x9e, 0x08, 0x69, 0xf7, 0x94, 0x1d, 0x2c, 0x14, 0x51, 0x79, 0xfe, 0x9e, 0xa7, 0x29, 0xd9, 0x30,
	0x69, 0x1f, 0xe8, 0xf3, 0x06, 0x89, 0x28, 0xfe, 0x1c, 0x46, 0xa5, 0x20, 0xa2, 0x2a, 0x83, 0xe1,
	0xb2, 0xb7, 0x9a, 0xbc, 0x3e, 0x7f, 0xf5, 0x78, 0xed, 0xeb, 0x2a, 0x4d, 0xa3, 0x4c, 0x7c, 0xf5,
	0x26, 0x36, 0x3e, 0xf8, 0x1c, 0x86, 0x29, 0xdf, 0x72, 0x11, 0x8c, 0x54, 0x1c, 0xbd, 0xc1, 0x18,
	0x06, 0x3b, 0xb2, 0x61, 0xc1, 0x58, 0x81, 0x6a, 0x8d, 0x9f, 0x03, 0x4a, 0xf3, 0x6c, 0xc3, 0x45,
	0x45, 0x59, 0xe0, 0xab, 0x8c, 0x1e, 0x01, 0xbc, 0x00, 0x3f, 0x25, 0x42, 0x1b, 0x91, 0x32, 0xd6,
	0xfb, 0x30, 0x85, 0x79, 0x5d, 0x9a, 0x72, 0x97, 0x67, 0x25, 0xc3, 0x2b, 0x18, 0x50, 0x22, 0x48,
	0xd0, 0x5b, 0x7a, 0xce, 0x15, 0x6f, 0xe4, 0xea, 0xfb, 0x3c, 0xff, 0x10, 0x2b, 0x0f, 0xfc, 0x05,
	0xf8, 0x5b, 0x26, 0x88, 0xf2, 0xee, 0xab, 0x84, 0xce, 0x1a, 0xde, 0x3f, 0x1b, 0x53, 0x5c, 0x3b,
	0x85, 0x6f, 0xc0, 0xb7, 0x68, 0x9d, 0x47, 0xaf, 0x91, 0xc7, 0x39, 0x0c, 0x45, 0x2e, 0x48, 0x6a,
	0x2a, 0xaf, 0x37, 0xe1, 0x5f, 0x7d, 0x40, 0xf5, 0xa7, 0xf1, 0x0c, 0xfa, 0x9c, 0x9a, 0x53, 0x7d,
	0x4e, 0xf1, 0x4b, 0x38, 0x51, 0xdf, 0x5c, 0x67, 0xd5, 0xf6, 0x96, 0x15, 0xa5, 0x3a, 0x8b, 0xe2,
	0xa9, 0x02, 0xaf, 0x35, 0x86, 0x97, 0x30, 0xa1, 0xac, 0x4c, 0x0a, 0xbe, 0x13, 0x3c, 0xcf, 0x14,
	0x71, 0x28, 0x6e, 0x42, 0xf2, 0x3a, 0x19, 0xd9, 0x32, 0xc5, 0x19, 0x8a, 0xd5, 0x1a, 0x07, 0x30,
	0x26, 0x94, 0x16, 0xac, 0xd4, 0x7c, 0xa1, 0xd8, 0x6e, 0x5b, 0x25, 0x1d, 0xb5, 0x4b, 0xda, 0x26,
	0x63, 0xec, 0x92, 0x71, 0x51, 0x4b, 0xc0, 0x57, 0x29, 0x58, 0xb2, 0x17, 0xe0, 0x27, 0x44, 0xb0,
	0x4d, 0x5e, 0x3c, 0x58, 0x92, 0xec, 0x5e, 0xda, 0xa4, 0xc6, 0x48, 0x96, 0xb0, 0x00, 0xb4, 0xcd,
	0xee, 0xc3, 0x10, 0x4e, 0xdf, 0x31, 0xf1, 0x96, 0x09, 0xc2, 0x53, 0xab, 0x6e, 0xa7, 0x44, 0xe1,
	0x3f, 0x03, 0x78, 0xd6, 0x70, 0x32, 0x3c, 0xff, 0x4f, 0x0b, 0xf9, 0x02, 0x20, 0x29, 0x18, 0x11,
	0x8c, 0xae, 0x89, 0x30, 0xa5, 0x44, 0x06, 0xb9, 0x12, 0xd2, 0x5c, 0xed, 0xa8, 0x35, 0xeb, 0x6a,
	0x22, 0x83, 0x5c, 0x09, 0xd9, 0xe1, 0xb6, 0xec, 0xb2, 0x83, 0x27, 0xba, 0xc3, 0x2d, 0x14, 0xa9,
	0x2a, 0xd5, 0x0e, 0x2a, 0xcf, 0xa9, 0xae, 0x92, 0x05, 0xaf, 0x65, 0xbe, 0x4d, 0xc2, 0x4e, 0xda,
	0x84, 0x39, 0x23, 0x66, 0xe6, 0x8e, 0x98, 0x4b, 0x98, 0x5a, 0xb3, 0x0a, 0x3f, 0xd7, 0x15, 0x36,
	0x98, 0x8a, 0xee, 0x4c, 0xa1, 0xd3, 0xbd, 0x29, 0xf4, 0x12, 0x4e, 0x6a, 0x07, 0x15, 0xe4, 0x99,
	0xbe, 0xa3, 0x05, 0x55, 0x94, 0xf6, 0xa8, 0xc2, 0xee, 0xa8, 0xba, 0x84, 0xa9, 0x35, 0xab, 0x10,
	0x67, 0xfa, 0x1e, 0x06, 0x93, 0x11, 0xc2, 0x3f, 0x3c, 0x38, 0xbb, 0xa2, 0xf4, 0xc6, 0x76, 0xbc,
	0x95, 0x9f, 0x55, 0x40, 0xaf, 0xa1, 0x80, 0x27, 0x89, 0xab, 0x21, 0x13, 0xaf, 0x2d, 0x13, 0x47,
	0x76, 0x83, 0x7d, 0xd9, 0xb5, 0xcb, 0x3a, 0x3c, 0x32, 0xb9, 0x47, 0x47, 0x26, 0xf7, 0xd8, 0x2d,
	0x47, 0x53, 0xa7, 0x7e, 0x97, 0x4e, 0x91, 0xab, 0xd3, 0x15, 0x9c, 0x26, 0xf9, 0x3d, 0x2b, 0xd6,
	0x7c, 0x2b, 0x83, 0xef, 0x88, 0xb8, 0x33, 0xb2, 0x9b, 0x29, 0x3c, 0x92, 0xf0, 0x0d, 0x11, 0x77,
	0x0d, 0x45, 0x4f, 0x5a, 0x8a, 0x76, 0x34, 0x39, 0x75, 0x35, 0x19, 0x7e, 0x0b, 0xb3, 0xf7, 0xca,
	0xb5, 0xee, 0x6d, 0x0c, 0x83, 0x24, 0xa7, 0x35, 0x05, 0x72, 0x2d, 0xab, 0xbb, 0x65, 0x65, 0x29,
	0x67, 0xae, 0x2e, 0xbe, 0xdd, 0x86, 0x7f, 0x7b, 0x70, 0xf1, 0xab, 0x6a, 0x81, 0x3d, 0x2e, 0xdd,
	0x21, 0x61, 0xb9, 0xed, 0x77, 0x71, 0xeb, 0x75, 0x73, 0x3b, 0xe8, 0xe4, 0x76, 0x78, 0x8c, 0xdb,
	0xd1, 0x11, 0x6e, 0xc7, 0x47, 0xb8, 0xf5, 0xbb, 0xb8, 0x45, 0x5d, 0xdc, 0xc2, 0x53, 0xb8, 0x9d,
	0x1c, 0xe4, 0xf6, 0xf1, 0xe5, 0x9f, 0x3e, 0xe1, 0xe5, 0x77, 0x18, 0x3f, 0xd9, 0x63, 0xfc, 0x1b,
	0x00, 0x79, 0xea, 0xbd, 0x28, 0x78, 0xb6, 0x91, 0xcf, 0xe6, 0x3d, 0x49, 0x2b, 0x4b, 0xb7, 0xde,
	0xe0, 0x8f, 0x60, 0xcc, 0xcb, 0x75, 0x56, 0xa5, 0xfa, 0x39, 0xf5, 0xe3, 0x11, 0x2f, 0xe5, 0xa1,
	0xf0, 0x6b, 0x40, 0xf5, 0x27, 0xdb, 0x67, 0xbd, 0x63, 0x67, 0x5f, 0xff, 0xee, 0xc1, 0x69, 0xfd,
	0x16, 0xff, 0x48, 0x32, 0x9a, 0xb2, 0x02, 0x7f, 0x07, 0x63, 0xf3, 0x13, 0x81, 0x3f, 0x6e, 0xe4,
	0xd5, 0xfe, 0xe7, 0x5a, 0x2c, 0x0e, 0x99, 0x8c, 0x5e, 0x7f, 0x00, 0x54, 0x3f, 0x50, 0xf8, 0x93,
	0xb6, 0x63, 0xeb, 0x6d, 0x5b, 0x3c, 0x3f, 0x6c, 0x34, 0x71, 0x22, 0x98, 0x36, 0x27, 0x12, 0xfe,
	0xb4, 0xe1, 0x7d, 0x60, 0x54, 0x2d, 0x9a, 0xd7, 0x75, 0x5a, 0xe8, 0x17, 0x98, 0x3b, 0x3d, 0x81,
	0x2f, 0x1b, 0xde, 0x87, 0xfb, 0xa5, 0x2b, 0x60, 0x04, 0xf3, 0xb7, 0x2c, 0x65, 0xcd, 0x80, 0x9d,
	0x99, 0xfe, 0x77, 0xa8, 0xdb, 0x91, 0xfa, 0xc7, 0xfd, 0xf2, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x3d, 0x4e, 0x0e, 0xd4, 0xf6, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PhoneBookHandlerClient is the client API for PhoneBookHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PhoneBookHandlerClient interface {
	GetList(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetListResponse, error)
	GetDetail(ctx context.Context, in *GetDetailRequest, opts ...grpc.CallOption) (*GetDetailResponse, error)
	AddPhonebook(ctx context.Context, in *AddPhonebookRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	UpdatePhonebook(ctx context.Context, in *UpdatePhonebookRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	DeletePhonebook(ctx context.Context, in *GetDetailRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type phoneBookHandlerClient struct {
	cc *grpc.ClientConn
}

func NewPhoneBookHandlerClient(cc *grpc.ClientConn) PhoneBookHandlerClient {
	return &phoneBookHandlerClient{cc}
}

func (c *phoneBookHandlerClient) GetList(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetListResponse, error) {
	out := new(GetListResponse)
	err := c.cc.Invoke(ctx, "/phonebook.PhoneBookHandler/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phoneBookHandlerClient) GetDetail(ctx context.Context, in *GetDetailRequest, opts ...grpc.CallOption) (*GetDetailResponse, error) {
	out := new(GetDetailResponse)
	err := c.cc.Invoke(ctx, "/phonebook.PhoneBookHandler/GetDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phoneBookHandlerClient) AddPhonebook(ctx context.Context, in *AddPhonebookRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/phonebook.PhoneBookHandler/AddPhonebook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phoneBookHandlerClient) UpdatePhonebook(ctx context.Context, in *UpdatePhonebookRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/phonebook.PhoneBookHandler/UpdatePhonebook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phoneBookHandlerClient) DeletePhonebook(ctx context.Context, in *GetDetailRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/phonebook.PhoneBookHandler/DeletePhonebook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PhoneBookHandlerServer is the server API for PhoneBookHandler service.
type PhoneBookHandlerServer interface {
	GetList(context.Context, *GetListRequest) (*GetListResponse, error)
	GetDetail(context.Context, *GetDetailRequest) (*GetDetailResponse, error)
	AddPhonebook(context.Context, *AddPhonebookRequest) (*StatusResponse, error)
	UpdatePhonebook(context.Context, *UpdatePhonebookRequest) (*StatusResponse, error)
	DeletePhonebook(context.Context, *GetDetailRequest) (*StatusResponse, error)
}

// UnimplementedPhoneBookHandlerServer can be embedded to have forward compatible implementations.
type UnimplementedPhoneBookHandlerServer struct {
}

func (*UnimplementedPhoneBookHandlerServer) GetList(ctx context.Context, req *GetListRequest) (*GetListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (*UnimplementedPhoneBookHandlerServer) GetDetail(ctx context.Context, req *GetDetailRequest) (*GetDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDetail not implemented")
}
func (*UnimplementedPhoneBookHandlerServer) AddPhonebook(ctx context.Context, req *AddPhonebookRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPhonebook not implemented")
}
func (*UnimplementedPhoneBookHandlerServer) UpdatePhonebook(ctx context.Context, req *UpdatePhonebookRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePhonebook not implemented")
}
func (*UnimplementedPhoneBookHandlerServer) DeletePhonebook(ctx context.Context, req *GetDetailRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePhonebook not implemented")
}

func RegisterPhoneBookHandlerServer(s *grpc.Server, srv PhoneBookHandlerServer) {
	s.RegisterService(&_PhoneBookHandler_serviceDesc, srv)
}

func _PhoneBookHandler_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhoneBookHandlerServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phonebook.PhoneBookHandler/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhoneBookHandlerServer).GetList(ctx, req.(*GetListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhoneBookHandler_GetDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhoneBookHandlerServer).GetDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phonebook.PhoneBookHandler/GetDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhoneBookHandlerServer).GetDetail(ctx, req.(*GetDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhoneBookHandler_AddPhonebook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPhonebookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhoneBookHandlerServer).AddPhonebook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phonebook.PhoneBookHandler/AddPhonebook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhoneBookHandlerServer).AddPhonebook(ctx, req.(*AddPhonebookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhoneBookHandler_UpdatePhonebook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePhonebookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhoneBookHandlerServer).UpdatePhonebook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phonebook.PhoneBookHandler/UpdatePhonebook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhoneBookHandlerServer).UpdatePhonebook(ctx, req.(*UpdatePhonebookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhoneBookHandler_DeletePhonebook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhoneBookHandlerServer).DeletePhonebook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phonebook.PhoneBookHandler/DeletePhonebook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhoneBookHandlerServer).DeletePhonebook(ctx, req.(*GetDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PhoneBookHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "phonebook.PhoneBookHandler",
	HandlerType: (*PhoneBookHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetList",
			Handler:    _PhoneBookHandler_GetList_Handler,
		},
		{
			MethodName: "GetDetail",
			Handler:    _PhoneBookHandler_GetDetail_Handler,
		},
		{
			MethodName: "AddPhonebook",
			Handler:    _PhoneBookHandler_AddPhonebook_Handler,
		},
		{
			MethodName: "UpdatePhonebook",
			Handler:    _PhoneBookHandler_UpdatePhonebook_Handler,
		},
		{
			MethodName: "DeletePhonebook",
			Handler:    _PhoneBookHandler_DeletePhonebook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "phonebook.proto",
}
