// Code generated by protoc-gen-go. DO NOT EDIT.
// source: video.proto

package video

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetListVideoRequest struct {
	RegencyId            int64    `protobuf:"varint,1,opt,name=regency_id,json=regencyId,proto3" json:"regency_id,omitempty"`
	Page                 int64    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListVideoRequest) Reset()         { *m = GetListVideoRequest{} }
func (m *GetListVideoRequest) String() string { return proto.CompactTextString(m) }
func (*GetListVideoRequest) ProtoMessage()    {}
func (*GetListVideoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{0}
}

func (m *GetListVideoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListVideoRequest.Unmarshal(m, b)
}
func (m *GetListVideoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListVideoRequest.Marshal(b, m, deterministic)
}
func (m *GetListVideoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListVideoRequest.Merge(m, src)
}
func (m *GetListVideoRequest) XXX_Size() int {
	return xxx_messageInfo_GetListVideoRequest.Size(m)
}
func (m *GetListVideoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListVideoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetListVideoRequest proto.InternalMessageInfo

func (m *GetListVideoRequest) GetRegencyId() int64 {
	if m != nil {
		return m.RegencyId
	}
	return 0
}

func (m *GetListVideoRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

type GetListVideoResponse struct {
	Data                 []*VideoList `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Metadata             *Metadata    `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetListVideoResponse) Reset()         { *m = GetListVideoResponse{} }
func (m *GetListVideoResponse) String() string { return proto.CompactTextString(m) }
func (*GetListVideoResponse) ProtoMessage()    {}
func (*GetListVideoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{1}
}

func (m *GetListVideoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListVideoResponse.Unmarshal(m, b)
}
func (m *GetListVideoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListVideoResponse.Marshal(b, m, deterministic)
}
func (m *GetListVideoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListVideoResponse.Merge(m, src)
}
func (m *GetListVideoResponse) XXX_Size() int {
	return xxx_messageInfo_GetListVideoResponse.Size(m)
}
func (m *GetListVideoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListVideoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetListVideoResponse proto.InternalMessageInfo

func (m *GetListVideoResponse) GetData() []*VideoList {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetListVideoResponse) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type VideoList struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CategoryId           int64    `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Source               string   `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	VideoUrl             string   `protobuf:"bytes,5,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	RegencyId            int64    `protobuf:"varint,6,opt,name=regency_id,json=regencyId,proto3" json:"regency_id,omitempty"`
	Status               int64    `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt            string   `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedBy            int64    `protobuf:"varint,10,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy            int64    `protobuf:"varint,11,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VideoList) Reset()         { *m = VideoList{} }
func (m *VideoList) String() string { return proto.CompactTextString(m) }
func (*VideoList) ProtoMessage()    {}
func (*VideoList) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{2}
}

func (m *VideoList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoList.Unmarshal(m, b)
}
func (m *VideoList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoList.Marshal(b, m, deterministic)
}
func (m *VideoList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoList.Merge(m, src)
}
func (m *VideoList) XXX_Size() int {
	return xxx_messageInfo_VideoList.Size(m)
}
func (m *VideoList) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoList.DiscardUnknown(m)
}

var xxx_messageInfo_VideoList proto.InternalMessageInfo

func (m *VideoList) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *VideoList) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *VideoList) GetCategoryId() int64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *VideoList) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *VideoList) GetVideoUrl() string {
	if m != nil {
		return m.VideoUrl
	}
	return ""
}

func (m *VideoList) GetRegencyId() int64 {
	if m != nil {
		return m.RegencyId
	}
	return 0
}

func (m *VideoList) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *VideoList) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *VideoList) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *VideoList) GetCreatedBy() int64 {
	if m != nil {
		return m.CreatedBy
	}
	return 0
}

func (m *VideoList) GetUpdatedBy() int64 {
	if m != nil {
		return m.UpdatedBy
	}
	return 0
}

type Metadata struct {
	Page                 int64    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	TotalPage            int64    `protobuf:"varint,2,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`
	Total                int64    `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{3}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Metadata) GetTotalPage() int64 {
	if m != nil {
		return m.TotalPage
	}
	return 0
}

func (m *Metadata) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type RequestID struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestID) Reset()         { *m = RequestID{} }
func (m *RequestID) String() string { return proto.CompactTextString(m) }
func (*RequestID) ProtoMessage()    {}
func (*RequestID) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{4}
}

func (m *RequestID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestID.Unmarshal(m, b)
}
func (m *RequestID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestID.Marshal(b, m, deterministic)
}
func (m *RequestID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestID.Merge(m, src)
}
func (m *RequestID) XXX_Size() int {
	return xxx_messageInfo_RequestID.Size(m)
}
func (m *RequestID) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestID.DiscardUnknown(m)
}

var xxx_messageInfo_RequestID proto.InternalMessageInfo

func (m *RequestID) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetDetailVideoResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CategoryId           int64    `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryName         string   `protobuf:"bytes,4,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	Source               string   `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	VideoUrl             string   `protobuf:"bytes,6,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	RegencyId            int64    `protobuf:"varint,7,opt,name=regency_id,json=regencyId,proto3" json:"regency_id,omitempty"`
	RegencyName          string   `protobuf:"bytes,8,opt,name=regency_name,json=regencyName,proto3" json:"regency_name,omitempty"`
	Status               int64    `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt            string   `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedBy            int64    `protobuf:"varint,12,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy            int64    `protobuf:"varint,13,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDetailVideoResponse) Reset()         { *m = GetDetailVideoResponse{} }
func (m *GetDetailVideoResponse) String() string { return proto.CompactTextString(m) }
func (*GetDetailVideoResponse) ProtoMessage()    {}
func (*GetDetailVideoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{5}
}

func (m *GetDetailVideoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDetailVideoResponse.Unmarshal(m, b)
}
func (m *GetDetailVideoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDetailVideoResponse.Marshal(b, m, deterministic)
}
func (m *GetDetailVideoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDetailVideoResponse.Merge(m, src)
}
func (m *GetDetailVideoResponse) XXX_Size() int {
	return xxx_messageInfo_GetDetailVideoResponse.Size(m)
}
func (m *GetDetailVideoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDetailVideoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDetailVideoResponse proto.InternalMessageInfo

func (m *GetDetailVideoResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetDetailVideoResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GetDetailVideoResponse) GetCategoryId() int64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *GetDetailVideoResponse) GetCategoryName() string {
	if m != nil {
		return m.CategoryName
	}
	return ""
}

func (m *GetDetailVideoResponse) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *GetDetailVideoResponse) GetVideoUrl() string {
	if m != nil {
		return m.VideoUrl
	}
	return ""
}

func (m *GetDetailVideoResponse) GetRegencyId() int64 {
	if m != nil {
		return m.RegencyId
	}
	return 0
}

func (m *GetDetailVideoResponse) GetRegencyName() string {
	if m != nil {
		return m.RegencyName
	}
	return ""
}

func (m *GetDetailVideoResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetDetailVideoResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetDetailVideoResponse) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *GetDetailVideoResponse) GetCreatedBy() int64 {
	if m != nil {
		return m.CreatedBy
	}
	return 0
}

func (m *GetDetailVideoResponse) GetUpdatedBy() int64 {
	if m != nil {
		return m.UpdatedBy
	}
	return 0
}

type NonRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NonRequest) Reset()         { *m = NonRequest{} }
func (m *NonRequest) String() string { return proto.CompactTextString(m) }
func (*NonRequest) ProtoMessage()    {}
func (*NonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{6}
}

func (m *NonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NonRequest.Unmarshal(m, b)
}
func (m *NonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NonRequest.Marshal(b, m, deterministic)
}
func (m *NonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NonRequest.Merge(m, src)
}
func (m *NonRequest) XXX_Size() int {
	return xxx_messageInfo_NonRequest.Size(m)
}
func (m *NonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NonRequest proto.InternalMessageInfo

type GetStatisticVideoResponse struct {
	Data                 []*VideoStatistic `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetStatisticVideoResponse) Reset()         { *m = GetStatisticVideoResponse{} }
func (m *GetStatisticVideoResponse) String() string { return proto.CompactTextString(m) }
func (*GetStatisticVideoResponse) ProtoMessage()    {}
func (*GetStatisticVideoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{7}
}

func (m *GetStatisticVideoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatisticVideoResponse.Unmarshal(m, b)
}
func (m *GetStatisticVideoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatisticVideoResponse.Marshal(b, m, deterministic)
}
func (m *GetStatisticVideoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatisticVideoResponse.Merge(m, src)
}
func (m *GetStatisticVideoResponse) XXX_Size() int {
	return xxx_messageInfo_GetStatisticVideoResponse.Size(m)
}
func (m *GetStatisticVideoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatisticVideoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatisticVideoResponse proto.InternalMessageInfo

func (m *GetStatisticVideoResponse) GetData() []*VideoStatistic {
	if m != nil {
		return m.Data
	}
	return nil
}

type VideoStatistic struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Count                int64    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VideoStatistic) Reset()         { *m = VideoStatistic{} }
func (m *VideoStatistic) String() string { return proto.CompactTextString(m) }
func (*VideoStatistic) ProtoMessage()    {}
func (*VideoStatistic) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{8}
}

func (m *VideoStatistic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoStatistic.Unmarshal(m, b)
}
func (m *VideoStatistic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoStatistic.Marshal(b, m, deterministic)
}
func (m *VideoStatistic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoStatistic.Merge(m, src)
}
func (m *VideoStatistic) XXX_Size() int {
	return xxx_messageInfo_VideoStatistic.Size(m)
}
func (m *VideoStatistic) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoStatistic.DiscardUnknown(m)
}

var xxx_messageInfo_VideoStatistic proto.InternalMessageInfo

func (m *VideoStatistic) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *VideoStatistic) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VideoStatistic) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type CreateVideoRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Source               string   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	CategoryId           int64    `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	RegencyId            int64    `protobuf:"varint,4,opt,name=regency_id,json=regencyId,proto3" json:"regency_id,omitempty"`
	VideoUrl             string   `protobuf:"bytes,5,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	Status               int64    `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateVideoRequest) Reset()         { *m = CreateVideoRequest{} }
func (m *CreateVideoRequest) String() string { return proto.CompactTextString(m) }
func (*CreateVideoRequest) ProtoMessage()    {}
func (*CreateVideoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{9}
}

func (m *CreateVideoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVideoRequest.Unmarshal(m, b)
}
func (m *CreateVideoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVideoRequest.Marshal(b, m, deterministic)
}
func (m *CreateVideoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVideoRequest.Merge(m, src)
}
func (m *CreateVideoRequest) XXX_Size() int {
	return xxx_messageInfo_CreateVideoRequest.Size(m)
}
func (m *CreateVideoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVideoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVideoRequest proto.InternalMessageInfo

func (m *CreateVideoRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateVideoRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *CreateVideoRequest) GetCategoryId() int64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *CreateVideoRequest) GetRegencyId() int64 {
	if m != nil {
		return m.RegencyId
	}
	return 0
}

func (m *CreateVideoRequest) GetVideoUrl() string {
	if m != nil {
		return m.VideoUrl
	}
	return ""
}

func (m *CreateVideoRequest) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

type StatusResponse struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{10}
}

func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (m *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(m, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *StatusResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*GetListVideoRequest)(nil), "video.GetListVideoRequest")
	proto.RegisterType((*GetListVideoResponse)(nil), "video.GetListVideoResponse")
	proto.RegisterType((*VideoList)(nil), "video.VideoList")
	proto.RegisterType((*Metadata)(nil), "video.Metadata")
	proto.RegisterType((*RequestID)(nil), "video.RequestID")
	proto.RegisterType((*GetDetailVideoResponse)(nil), "video.GetDetailVideoResponse")
	proto.RegisterType((*NonRequest)(nil), "video.NonRequest")
	proto.RegisterType((*GetStatisticVideoResponse)(nil), "video.GetStatisticVideoResponse")
	proto.RegisterType((*VideoStatistic)(nil), "video.VideoStatistic")
	proto.RegisterType((*CreateVideoRequest)(nil), "video.CreateVideoRequest")
	proto.RegisterType((*StatusResponse)(nil), "video.StatusResponse")
}

func init() { proto.RegisterFile("video.proto", fileDescriptor_0ad4ea8866efb1e3) }

var fileDescriptor_0ad4ea8866efb1e3 = []byte{
	// 637 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0x65, 0xc7, 0x49, 0xe3, 0xb1, 0x1b, 0xe8, 0x52, 0x2a, 0x37, 0x55, 0x45, 0x31, 0x1c,
	0x8a, 0x90, 0x7a, 0x28, 0x77, 0xa4, 0x96, 0x8a, 0x34, 0x08, 0x22, 0xe4, 0x08, 0xae, 0xd1, 0xc6,
	0x5e, 0x45, 0x96, 0x1c, 0x3b, 0xd8, 0x6b, 0x50, 0x9e, 0x82, 0xd7, 0xe0, 0x0d, 0x90, 0x78, 0x3a,
	0xe4, 0xd9, 0x5d, 0x7f, 0x25, 0x35, 0x17, 0x6e, 0x3b, 0x9f, 0x59, 0xcf, 0xef, 0x3f, 0x1b, 0xb0,
	0xbe, 0x87, 0x01, 0x4b, 0xae, 0x36, 0x69, 0xc2, 0x13, 0xd2, 0x47, 0xc3, 0xbd, 0x87, 0x27, 0x13,
	0xc6, 0x3f, 0x86, 0x19, 0xff, 0x5a, 0xd8, 0x1e, 0xfb, 0x96, 0xb3, 0x8c, 0x93, 0x73, 0x80, 0x94,
	0xad, 0x58, 0xec, 0x6f, 0x17, 0x61, 0xe0, 0x68, 0x17, 0xda, 0x65, 0xcf, 0x33, 0xa5, 0x67, 0x1a,
	0x10, 0x02, 0xc6, 0x86, 0xae, 0x98, 0xa3, 0x63, 0x00, 0xcf, 0x6e, 0x08, 0xc7, 0xcd, 0x4e, 0xd9,
	0x26, 0x89, 0x33, 0x46, 0x5e, 0x82, 0x11, 0x50, 0x4e, 0x1d, 0xed, 0xa2, 0x77, 0x69, 0x5d, 0x3f,
	0xbe, 0x12, 0x97, 0xc0, 0x9c, 0x22, 0xd9, 0xc3, 0x28, 0x79, 0x0d, 0xc3, 0x35, 0xe3, 0x14, 0x33,
	0x8b, 0xae, 0xd6, 0xf5, 0x23, 0x99, 0xf9, 0x49, 0xba, 0xbd, 0x32, 0xc1, 0xfd, 0xa3, 0x83, 0x59,
	0x36, 0x20, 0x23, 0xd0, 0xcb, 0x3b, 0xea, 0x61, 0x40, 0x8e, 0xa1, 0xcf, 0x43, 0x1e, 0x89, 0xdb,
	0x99, 0x9e, 0x30, 0xc8, 0x33, 0xb0, 0x7c, 0xca, 0xd9, 0x2a, 0x49, 0xf1, 0x93, 0x7a, 0x98, 0x0e,
	0xca, 0x35, 0x0d, 0xc8, 0x09, 0x0c, 0xb2, 0x24, 0x4f, 0x7d, 0xe6, 0x18, 0x58, 0x27, 0x2d, 0x72,
	0x06, 0x26, 0x5e, 0x64, 0x91, 0xa7, 0x91, 0xd3, 0xc7, 0xd0, 0x10, 0x1d, 0x5f, 0xd2, 0xa8, 0x35,
	0xa7, 0x41, 0x7b, 0x4e, 0x45, 0x4f, 0x4e, 0x79, 0x9e, 0x39, 0x07, 0x18, 0x92, 0x56, 0x51, 0xe6,
	0xa7, 0x8c, 0x72, 0x16, 0x2c, 0x28, 0x77, 0x86, 0xd8, 0xd4, 0x94, 0x9e, 0x1b, 0x9c, 0x7e, 0xbe,
	0x09, 0x54, 0xd8, 0x14, 0x61, 0xe9, 0x11, 0x61, 0x55, 0xbd, 0xdc, 0x3a, 0x20, 0x7e, 0x54, 0x7a,
	0x6e, 0xb7, 0xf5, 0xea, 0xe5, 0xd6, 0xb1, 0x44, 0x58, 0x7a, 0x6e, 0xb7, 0xee, 0x1c, 0x86, 0x6a,
	0xa4, 0x25, 0x47, 0xad, 0xe2, 0x58, 0x94, 0xf3, 0x84, 0xd3, 0x68, 0x51, 0x23, 0x6c, 0xa2, 0xe7,
	0x73, 0x11, 0x2e, 0xa6, 0x5b, 0x18, 0x72, 0x82, 0xc2, 0x70, 0xcf, 0xc0, 0x94, 0xd2, 0x99, 0xde,
	0xb5, 0x81, 0xb8, 0x3f, 0x7b, 0x70, 0x32, 0x61, 0xfc, 0x8e, 0x71, 0x1a, 0x46, 0x4d, 0x71, 0xfc,
	0x27, 0x76, 0x2f, 0xe0, 0xb0, 0x4c, 0x88, 0xe9, 0x5a, 0x21, 0xb4, 0x95, 0x73, 0x46, 0xd7, 0xac,
	0x06, 0xb8, 0xff, 0x30, 0xe0, 0x41, 0x27, 0xe0, 0x83, 0x36, 0xe0, 0xe7, 0x60, 0xab, 0x30, 0xfe,
	0xae, 0x40, 0x69, 0x49, 0x5f, 0xf9, 0xb3, 0x42, 0x03, 0x66, 0x87, 0x06, 0xa0, 0x5b, 0x03, 0x56,
	0xb7, 0x06, 0xec, 0x6e, 0x0d, 0x1c, 0xb6, 0x35, 0x60, 0x03, 0xcc, 0x92, 0x58, 0x12, 0x73, 0xdf,
	0xc3, 0xe9, 0x84, 0xf1, 0x39, 0xa7, 0x3c, 0xcc, 0x78, 0xe8, 0x37, 0x09, 0xbd, 0x6a, 0xac, 0xef,
	0xd3, 0xfa, 0xfa, 0x96, 0x15, 0x62, 0x87, 0xdd, 0x0f, 0x30, 0x6a, 0xfa, 0x77, 0xf0, 0x12, 0x30,
	0x70, 0x4c, 0x82, 0x2e, 0x9e, 0x0b, 0xe4, 0x7e, 0x92, 0xc7, 0x5c, 0x09, 0x0a, 0x0d, 0xf7, 0xb7,
	0x06, 0xe4, 0x1d, 0x7e, 0x4e, 0xe3, 0x5d, 0x2a, 0xf5, 0xa1, 0xd5, 0xf5, 0x51, 0x91, 0xd5, 0x1b,
	0x64, 0xff, 0xa9, 0x9b, 0x26, 0x5d, 0xa3, 0x4d, 0xb7, 0x73, 0xf5, 0x2b, 0xae, 0x83, 0x3a, 0x57,
	0xf7, 0x2d, 0x8c, 0xe6, 0x78, 0x2a, 0x47, 0x48, 0xc0, 0xf0, 0x93, 0x40, 0xdd, 0x19, 0xcf, 0xc4,
	0x81, 0x83, 0x35, 0xcb, 0x32, 0xb5, 0x62, 0xa6, 0xa7, 0xcc, 0xeb, 0x5f, 0x3a, 0xd8, 0xf8, 0xcd,
	0xf7, 0x34, 0x0e, 0x22, 0x96, 0x92, 0x09, 0xd8, 0xf5, 0x87, 0x95, 0x8c, 0x25, 0x83, 0x3d, 0xef,
	0xf6, 0xf8, 0x6c, 0x6f, 0x4c, 0xde, 0xe3, 0x06, 0x46, 0xcd, 0x35, 0x24, 0xea, 0x35, 0x2e, 0x77,
	0x77, 0x7c, 0x5e, 0x35, 0xd8, 0xb7, 0xaf, 0xf7, 0x70, 0xb4, 0x23, 0x15, 0x72, 0x24, 0x6b, 0x2a,
	0x49, 0x8d, 0x2f, 0xaa, 0x36, 0x0f, 0xe8, 0xea, 0x16, 0x46, 0x82, 0xef, 0x8c, 0xfd, 0x10, 0x6d,
	0x4e, 0x65, 0xcd, 0x2e, 0xf6, 0xb1, 0x92, 0x5d, 0x73, 0xb0, 0xcb, 0x01, 0xfe, 0x95, 0xbd, 0xf9,
	0x1b, 0x00, 0x00, 0xff, 0xff, 0x9b, 0x54, 0x30, 0xca, 0xd9, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VideoHandlerClient is the client API for VideoHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VideoHandlerClient interface {
	GetListVideo(ctx context.Context, in *GetListVideoRequest, opts ...grpc.CallOption) (*GetListVideoResponse, error)
	GetDetailVideo(ctx context.Context, in *RequestID, opts ...grpc.CallOption) (*GetDetailVideoResponse, error)
	GetStatisticVideo(ctx context.Context, in *NonRequest, opts ...grpc.CallOption) (*GetStatisticVideoResponse, error)
	CreateNewVideo(ctx context.Context, in *CreateVideoRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type videoHandlerClient struct {
	cc *grpc.ClientConn
}

func NewVideoHandlerClient(cc *grpc.ClientConn) VideoHandlerClient {
	return &videoHandlerClient{cc}
}

func (c *videoHandlerClient) GetListVideo(ctx context.Context, in *GetListVideoRequest, opts ...grpc.CallOption) (*GetListVideoResponse, error) {
	out := new(GetListVideoResponse)
	err := c.cc.Invoke(ctx, "/video.VideoHandler/GetListVideo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoHandlerClient) GetDetailVideo(ctx context.Context, in *RequestID, opts ...grpc.CallOption) (*GetDetailVideoResponse, error) {
	out := new(GetDetailVideoResponse)
	err := c.cc.Invoke(ctx, "/video.VideoHandler/GetDetailVideo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoHandlerClient) GetStatisticVideo(ctx context.Context, in *NonRequest, opts ...grpc.CallOption) (*GetStatisticVideoResponse, error) {
	out := new(GetStatisticVideoResponse)
	err := c.cc.Invoke(ctx, "/video.VideoHandler/GetStatisticVideo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoHandlerClient) CreateNewVideo(ctx context.Context, in *CreateVideoRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/video.VideoHandler/CreateNewVideo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoHandlerServer is the server API for VideoHandler service.
type VideoHandlerServer interface {
	GetListVideo(context.Context, *GetListVideoRequest) (*GetListVideoResponse, error)
	GetDetailVideo(context.Context, *RequestID) (*GetDetailVideoResponse, error)
	GetStatisticVideo(context.Context, *NonRequest) (*GetStatisticVideoResponse, error)
	CreateNewVideo(context.Context, *CreateVideoRequest) (*StatusResponse, error)
}

// UnimplementedVideoHandlerServer can be embedded to have forward compatible implementations.
type UnimplementedVideoHandlerServer struct {
}

func (*UnimplementedVideoHandlerServer) GetListVideo(ctx context.Context, req *GetListVideoRequest) (*GetListVideoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListVideo not implemented")
}
func (*UnimplementedVideoHandlerServer) GetDetailVideo(ctx context.Context, req *RequestID) (*GetDetailVideoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDetailVideo not implemented")
}
func (*UnimplementedVideoHandlerServer) GetStatisticVideo(ctx context.Context, req *NonRequest) (*GetStatisticVideoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatisticVideo not implemented")
}
func (*UnimplementedVideoHandlerServer) CreateNewVideo(ctx context.Context, req *CreateVideoRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNewVideo not implemented")
}

func RegisterVideoHandlerServer(s *grpc.Server, srv VideoHandlerServer) {
	s.RegisterService(&_VideoHandler_serviceDesc, srv)
}

func _VideoHandler_GetListVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoHandlerServer).GetListVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video.VideoHandler/GetListVideo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoHandlerServer).GetListVideo(ctx, req.(*GetListVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoHandler_GetDetailVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoHandlerServer).GetDetailVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video.VideoHandler/GetDetailVideo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoHandlerServer).GetDetailVideo(ctx, req.(*RequestID))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoHandler_GetStatisticVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoHandlerServer).GetStatisticVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video.VideoHandler/GetStatisticVideo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoHandlerServer).GetStatisticVideo(ctx, req.(*NonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoHandler_CreateNewVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoHandlerServer).CreateNewVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video.VideoHandler/CreateNewVideo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoHandlerServer).CreateNewVideo(ctx, req.(*CreateVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VideoHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "video.VideoHandler",
	HandlerType: (*VideoHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetListVideo",
			Handler:    _VideoHandler_GetListVideo_Handler,
		},
		{
			MethodName: "GetDetailVideo",
			Handler:    _VideoHandler_GetDetailVideo_Handler,
		},
		{
			MethodName: "GetStatisticVideo",
			Handler:    _VideoHandler_GetStatisticVideo_Handler,
		},
		{
			MethodName: "CreateNewVideo",
			Handler:    _VideoHandler_CreateNewVideo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "video.proto",
}
